const elements = [
  {
    "number": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "atomicMass": 1.008,
    "electronConfiguration": "1s1",
    "group": 1,
    "period": 1,
    "category": "diatomic nonmetal",
    "block": "s"
  },
  {
    "number": 2,
    "symbol": "He",
    "name": "Helium",
    "atomicMass": 4.0026022,
    "electronConfiguration": "1s2",
    "group": 18,
    "period": 1,
    "category": "noble gas",
    "block": "s"
  },
  {
    "number": 3,
    "symbol": "Li",
    "name": "Lithium",
    "atomicMass": 6.94,
    "electronConfiguration": "[He] 2s1",
    "group": 1,
    "period": 2,
    "category": "alkali metal",
    "block": "s"
  },
  {
    "number": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "atomicMass": 9.01218315,
    "electronConfiguration": "[He] 2s2",
    "group": 2,
    "period": 2,
    "category": "alkaline earth metal",
    "block": "s"
  },
  {
    "number": 5,
    "symbol": "B",
    "name": "Boron",
    "atomicMass": 10.81,
    "electronConfiguration": "[He] 2s2 2p1",
    "group": 13,
    "period": 2,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 6,
    "symbol": "C",
    "name": "Carbon",
    "atomicMass": 12.011,
    "electronConfiguration": "[He] 2s2 2p2",
    "group": 14,
    "period": 2,
    "category": "polyatomic nonmetal",
    "block": "p"
  },
  {
    "number": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "atomicMass": 14.007,
    "electronConfiguration": "[He] 2s2 2p3",
    "group": 15,
    "period": 2,
    "category": "diatomic nonmetal",
    "block": "p"
  },
  {
    "number": 8,
    "symbol": "O",
    "name": "Oxygen",
    "atomicMass": 15.999,
    "electronConfiguration": "[He] 2s2 2p4",
    "group": 16,
    "period": 2,
    "category": "diatomic nonmetal",
    "block": "p"
  },
  {
    "number": 9,
    "symbol": "F",
    "name": "Fluorine",
    "atomicMass": 18.9984031636,
    "electronConfiguration": "[He] 2s2 2p5",
    "group": 17,
    "period": 2,
    "category": "diatomic nonmetal",
    "block": "p"
  },
  {
    "number": 10,
    "symbol": "Ne",
    "name": "Neon",
    "atomicMass": 20.17976,
    "electronConfiguration": "[He] 2s2 2p6",
    "group": 18,
    "period": 2,
    "category": "noble gas",
    "block": "p"
  },
  {
    "number": 11,
    "symbol": "Na",
    "name": "Sodium",
    "atomicMass": 22.989769282,
    "electronConfiguration": "[Ne] 3s1",
    "group": 1,
    "period": 3,
    "category": "alkali metal",
    "block": "s"
  },
  {
    "number": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "atomicMass": 24.305,
    "electronConfiguration": "[Ne] 3s2",
    "group": 2,
    "period": 3,
    "category": "alkaline earth metal",
    "block": "s"
  },
  {
    "number": 13,
    "symbol": "Al",
    "name": "Aluminium",
    "atomicMass": 26.98153857,
    "electronConfiguration": "[Ne] 3s2 3p1",
    "group": 13,
    "period": 3,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 14,
    "symbol": "Si",
    "name": "Silicon",
    "atomicMass": 28.085,
    "electronConfiguration": "[Ne] 3s2 3p2",
    "group": 14,
    "period": 3,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "atomicMass": 30.9737619985,
    "electronConfiguration": "[Ne] 3s2 3p3",
    "group": 15,
    "period": 3,
    "category": "polyatomic nonmetal",
    "block": "p"
  },
  {
    "number": 16,
    "symbol": "S",
    "name": "Sulfur",
    "atomicMass": 32.06,
    "electronConfiguration": "[Ne] 3s2 3p4",
    "group": 16,
    "period": 3,
    "category": "polyatomic nonmetal",
    "block": "p"
  },
  {
    "number": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "atomicMass": 35.45,
    "electronConfiguration": "[Ne] 3s2 3p5",
    "group": 17,
    "period": 3,
    "category": "diatomic nonmetal",
    "block": "p"
  },
  {
    "number": 18,
    "symbol": "Ar",
    "name": "Argon",
    "atomicMass": 39.9481,
    "electronConfiguration": "[Ne] 3s2 3p6",
    "group": 18,
    "period": 3,
    "category": "noble gas",
    "block": "p"
  },
  {
    "number": 19,
    "symbol": "K",
    "name": "Potassium",
    "atomicMass": 39.09831,
    "electronConfiguration": "[Ar] 4s1",
    "group": 1,
    "period": 4,
    "category": "alkali metal",
    "block": "s"
  },
  {
    "number": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "atomicMass": 40.0784,
    "electronConfiguration": "[Ar] 4s2",
    "group": 2,
    "period": 4,
    "category": "alkaline earth metal",
    "block": "s"
  },
  {
    "number": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "atomicMass": 44.9559085,
    "electronConfiguration": "[Ar] 3d1 4s2",
    "group": 3,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "atomicMass": 47.8671,
    "electronConfiguration": "[Ar] 3d2 4s2",
    "group": 4,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 23,
    "symbol": "V",
    "name": "Vanadium",
    "atomicMass": 50.94151,
    "electronConfiguration": "[Ar] 3d3 4s2",
    "group": 5,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "atomicMass": 51.99616,
    "electronConfiguration": "[Ar] 3d5 4s1",
    "group": 6,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "atomicMass": 54.9380443,
    "electronConfiguration": "[Ar] 3d5 4s2",
    "group": 7,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 26,
    "symbol": "Fe",
    "name": "Iron",
    "atomicMass": 55.8452,
    "electronConfiguration": "[Ar] 3d6 4s2",
    "group": 8,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "atomicMass": 58.9331944,
    "electronConfiguration": "[Ar] 3d7 4s2",
    "group": 9,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "atomicMass": 58.69344,
    "electronConfiguration": "[Ar] 3d8 4s2",
    "group": 10,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 29,
    "symbol": "Cu",
    "name": "Copper",
    "atomicMass": 63.5463,
    "electronConfiguration": "[Ar] 3d10 4s1",
    "group": 11,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "atomicMass": 65.382,
    "electronConfiguration": "[Ar] 3d10 4s2",
    "group": 12,
    "period": 4,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "atomicMass": 69.7231,
    "electronConfiguration": "[Ar] 3d10 4s2 4p1",
    "group": 13,
    "period": 4,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "atomicMass": 72.6308,
    "electronConfiguration": "[Ar] 3d10 4s2 4p2",
    "group": 14,
    "period": 4,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 33,
    "symbol": "As",
    "name": "Arsenic",
    "atomicMass": 74.9215956,
    "electronConfiguration": "[Ar] 3d10 4s2 4p3",
    "group": 15,
    "period": 4,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 34,
    "symbol": "Se",
    "name": "Selenium",
    "atomicMass": 78.9718,
    "electronConfiguration": "[Ar] 3d10 4s2 4p4",
    "group": 16,
    "period": 4,
    "category": "polyatomic nonmetal",
    "block": "p"
  },
  {
    "number": 35,
    "symbol": "Br",
    "name": "Bromine",
    "atomicMass": 79.904,
    "electronConfiguration": "[Ar] 3d10 4s2 4p5",
    "group": 17,
    "period": 4,
    "category": "diatomic nonmetal",
    "block": "p"
  },
  {
    "number": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "atomicMass": 83.7982,
    "electronConfiguration": "[Ar] 3d10 4s2 4p6",
    "group": 18,
    "period": 4,
    "category": "noble gas",
    "block": "p"
  },
  {
    "number": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "atomicMass": 85.46783,
    "electronConfiguration": "[Kr] 5s1",
    "group": 1,
    "period": 5,
    "category": "alkali metal",
    "block": "s"
  },
  {
    "number": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "atomicMass": 87.621,
    "electronConfiguration": "[Kr] 5s2",
    "group": 2,
    "period": 5,
    "category": "alkaline earth metal",
    "block": "s"
  },
  {
    "number": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "atomicMass": 88.905842,
    "electronConfiguration": "[Kr] 4d1 5s2",
    "group": 3,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "atomicMass": 91.2242,
    "electronConfiguration": "[Kr] 4d2 5s2",
    "group": 4,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "atomicMass": 92.906372,
    "electronConfiguration": "[Kr] 4d4 5s1",
    "group": 5,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "atomicMass": 95.951,
    "electronConfiguration": "[Kr] 4d5 5s1",
    "group": 6,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "atomicMass": 98,
    "electronConfiguration": "[Kr] 4d5 5s2",
    "group": 7,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "atomicMass": 101.072,
    "electronConfiguration": "[Kr] 4d7 5s1",
    "group": 8,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "atomicMass": 102.905502,
    "electronConfiguration": "[Kr] 4d8 5s1",
    "group": 9,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "atomicMass": 106.421,
    "electronConfiguration": "[Kr] 4d10",
    "group": 10,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 47,
    "symbol": "Ag",
    "name": "Silver",
    "atomicMass": 107.86822,
    "electronConfiguration": "[Kr] 4d10 5s1",
    "group": 11,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "atomicMass": 112.4144,
    "electronConfiguration": "[Kr] 4d10 5s2",
    "group": 12,
    "period": 5,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 49,
    "symbol": "In",
    "name": "Indium",
    "atomicMass": 114.8181,
    "electronConfiguration": "[Kr] 4d10 5s2 5p1",
    "group": 13,
    "period": 5,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 50,
    "symbol": "Sn",
    "name": "Tin",
    "atomicMass": 118.7107,
    "electronConfiguration": "[Kr] 4d10 5s2 5p2",
    "group": 14,
    "period": 5,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "atomicMass": 121.7601,
    "electronConfiguration": "[Kr] 4d10 5s2 5p3",
    "group": 15,
    "period": 5,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "atomicMass": 127.603,
    "electronConfiguration": "[Kr] 4d10 5s2 5p4",
    "group": 16,
    "period": 5,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 53,
    "symbol": "I",
    "name": "Iodine",
    "atomicMass": 126.904473,
    "electronConfiguration": "[Kr] 4d10 5s2 5p5",
    "group": 17,
    "period": 5,
    "category": "diatomic nonmetal",
    "block": "p"
  },
  {
    "number": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "atomicMass": 131.2936,
    "electronConfiguration": "[Kr] 4d10 5s2 5p6",
    "group": 18,
    "period": 5,
    "category": "noble gas",
    "block": "p"
  },
  {
    "number": 55,
    "symbol": "Cs",
    "name": "Cesium",
    "atomicMass": 132.905451966,
    "electronConfiguration": "[Xe] 6s1",
    "group": 1,
    "period": 6,
    "category": "alkali metal",
    "block": "s"
  },
  {
    "number": 56,
    "symbol": "Ba",
    "name": "Barium",
    "atomicMass": 137.3277,
    "electronConfiguration": "[Xe] 6s2",
    "group": 2,
    "period": 6,
    "category": "alkaline earth metal",
    "block": "s"
  },
  {
    "number": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "atomicMass": 138.905477,
    "electronConfiguration": "[Xe] 5d16s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "atomicMass": 140.1161,
    "electronConfiguration": "[Xe] 4f1 5d1 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "atomicMass": 140.907662,
    "electronConfiguration": "[Xe] 4f3 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "atomicMass": 144.2423,
    "electronConfiguration": "[Xe] 4f4 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "atomicMass": 145,
    "electronConfiguration": "[Xe] 4f5 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "atomicMass": 150.362,
    "electronConfiguration": "[Xe] 4f6 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 63,
    "symbol": "Eu",
    "name": "Europium",
    "atomicMass": 151.9641,
    "electronConfiguration": "[Xe] 4f7 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "atomicMass": 157.253,
    "electronConfiguration": "[Xe] 4f7 5d1 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "atomicMass": 158.925352,
    "electronConfiguration": "[Xe] 4f9 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "atomicMass": 162.5001,
    "electronConfiguration": "[Xe] 4f10 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "atomicMass": 164.930332,
    "electronConfiguration": "[Xe] 4f11 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 68,
    "symbol": "Er",
    "name": "Erbium",
    "atomicMass": 167.2593,
    "electronConfiguration": "[Xe] 4f12 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "atomicMass": 168.934222,
    "electronConfiguration": "[Xe] 4f13 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "atomicMass": 173.0451,
    "electronConfiguration": "[Xe] 4f14 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "f"
  },
  {
    "number": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "atomicMass": 174.96681,
    "electronConfiguration": "[Xe] 4f14 5d1 6s2",
    "group": 3,
    "period": 6,
    "category": "lanthanide",
    "block": "d"
  },
  {
    "number": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "atomicMass": 178.492,
    "electronConfiguration": "[Xe] 4f14 5d2 6s2",
    "group": 4,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "atomicMass": 180.947882,
    "electronConfiguration": "[Xe] 4f14 5d3 6s2",
    "group": 5,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 74,
    "symbol": "W",
    "name": "Tungsten",
    "atomicMass": 183.841,
    "electronConfiguration": "[Xe] 4f14 5d4 6s2",
    "group": 6,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "atomicMass": 186.2071,
    "electronConfiguration": "[Xe] 4f14 5d5 6s2",
    "group": 7,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 76,
    "symbol": "Os",
    "name": "Osmium",
    "atomicMass": 190.233,
    "electronConfiguration": "[Xe] 4f14 5d6 6s2",
    "group": 8,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "atomicMass": 192.2173,
    "electronConfiguration": "[Xe] 4f14 5d7 6s2",
    "group": 9,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "atomicMass": 195.0849,
    "electronConfiguration": "[Xe] 4f14 5d9 6s1",
    "group": 10,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 79,
    "symbol": "Au",
    "name": "Gold",
    "atomicMass": 196.9665695,
    "electronConfiguration": "[Xe] 4f14 5d10 6s1",
    "group": 11,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "atomicMass": 200.5923,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2",
    "group": 12,
    "period": 6,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "atomicMass": 204.38,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p1",
    "group": 13,
    "period": 6,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 82,
    "symbol": "Pb",
    "name": "Lead",
    "atomicMass": 207.21,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
    "group": 14,
    "period": 6,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "atomicMass": 208.980401,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
    "group": 15,
    "period": 6,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 84,
    "symbol": "Po",
    "name": "Polonium",
    "atomicMass": 209,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
    "group": 16,
    "period": 6,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 85,
    "symbol": "At",
    "name": "Astatine",
    "atomicMass": 210,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
    "group": 17,
    "period": 6,
    "category": "metalloid",
    "block": "p"
  },
  {
    "number": 86,
    "symbol": "Rn",
    "name": "Radon",
    "atomicMass": 222,
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
    "group": 18,
    "period": 6,
    "category": "noble gas",
    "block": "p"
  },
  {
    "number": 87,
    "symbol": "Fr",
    "name": "Francium",
    "atomicMass": 223,
    "electronConfiguration": "[Rn] 7s1",
    "group": 1,
    "period": 7,
    "category": "alkali metal",
    "block": "s"
  },
  {
    "number": 88,
    "symbol": "Ra",
    "name": "Radium",
    "atomicMass": 226,
    "electronConfiguration": "[Rn] 7s2",
    "group": 2,
    "period": 7,
    "category": "alkaline earth metal",
    "block": "s"
  },
  {
    "number": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "atomicMass": 227,
    "electronConfiguration": "[Rn] 6d1 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 90,
    "symbol": "Th",
    "name": "Thorium",
    "atomicMass": 232.03774,
    "electronConfiguration": "[Rn] 6d2 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "atomicMass": 231.035882,
    "electronConfiguration": "[Rn] 5f2 6d1 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 92,
    "symbol": "U",
    "name": "Uranium",
    "atomicMass": 238.028913,
    "electronConfiguration": "[Rn] 5f3 6d1 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "atomicMass": 237,
    "electronConfiguration": "[Rn] 5f4 6d1 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "atomicMass": 244,
    "electronConfiguration": "[Rn] 5f6 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 95,
    "symbol": "Am",
    "name": "Americium",
    "atomicMass": 243,
    "electronConfiguration": "[Rn] 5f7 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 96,
    "symbol": "Cm",
    "name": "Curium",
    "atomicMass": 247,
    "electronConfiguration": "[Rn] 5f7 6d1 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "atomicMass": 247,
    "electronConfiguration": "[Rn] 5f9 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 98,
    "symbol": "Cf",
    "name": "Californium",
    "atomicMass": 251,
    "electronConfiguration": "[Rn] 5f10 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "atomicMass": 252,
    "electronConfiguration": "[Rn] 5f11 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "atomicMass": 257,
    "electronConfiguration": "[Rn] 5f12 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "atomicMass": 258,
    "electronConfiguration": "[Rn] 5f13 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 102,
    "symbol": "No",
    "name": "Nobelium",
    "atomicMass": 259,
    "electronConfiguration": "[Rn] 5f14 7s2",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "f"
  },
  {
    "number": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "atomicMass": 266,
    "electronConfiguration": "[Rn] 5f14 7s2 7p1",
    "group": 3,
    "period": 7,
    "category": "actinide",
    "block": "d"
  },
  {
    "number": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "atomicMass": 267,
    "electronConfiguration": "[Rn] 5f14 6d2 7s2",
    "group": 4,
    "period": 7,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "atomicMass": 268,
    "electronConfiguration": "*[Rn] 5f14 6d3 7s2",
    "group": 5,
    "period": 7,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "atomicMass": 269,
    "electronConfiguration": "*[Rn] 5f14 6d4 7s2",
    "group": 6,
    "period": 7,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "atomicMass": 270,
    "electronConfiguration": "*[Rn] 5f14 6d5 7s2",
    "group": 7,
    "period": 7,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "atomicMass": 269,
    "electronConfiguration": "*[Rn] 5f14 6d6 7s2",
    "group": 8,
    "period": 7,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "atomicMass": 278,
    "electronConfiguration": "*[Rn] 5f14 6d7 7s2",
    "group": 9,
    "period": 7,
    "category": "unknown, probably transition metal",
    "block": "d"
  },
  {
    "number": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "atomicMass": 281,
    "electronConfiguration": "*[Rn] 5f14 6d9 7s1",
    "group": 10,
    "period": 7,
    "category": "unknown, probably transition metal",
    "block": "d"
  },
  {
    "number": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "atomicMass": 282,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s1",
    "group": 11,
    "period": 7,
    "category": "unknown, probably transition metal",
    "block": "d"
  },
  {
    "number": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "atomicMass": 285,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2",
    "group": 12,
    "period": 7,
    "category": "transition metal",
    "block": "d"
  },
  {
    "number": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "atomicMass": 286,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2 7p1",
    "group": 13,
    "period": 7,
    "category": "unknown, probably transition metal",
    "block": "p"
  },
  {
    "number": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "atomicMass": 289,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2 7p2",
    "group": 14,
    "period": 7,
    "category": "post-transition metal",
    "block": "p"
  },
  {
    "number": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "atomicMass": 289,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2 7p3",
    "group": 15,
    "period": 7,
    "category": "unknown, probably post-transition metal",
    "block": "p"
  },
  {
    "number": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "atomicMass": 293,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2 7p4",
    "group": 16,
    "period": 7,
    "category": "unknown, probably post-transition metal",
    "block": "p"
  },
  {
    "number": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "atomicMass": 294,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2 7p5",
    "group": 17,
    "period": 7,
    "category": "unknown, probably metalloid",
    "block": "p"
  },
  {
    "number": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "atomicMass": 294,
    "electronConfiguration": "*[Rn] 5f14 6d10 7s2 7p6",
    "group": 18,
    "period": 7,
    "category": "unknown, predicted to be noble gas",
    "block": "p"
  },
  {
    "number": 119,
    "symbol": "Uue",
    "name": "Ununennium",
    "atomicMass": 315,
    "electronConfiguration": "*[Uuo] 8s1",
    "group": 1,
    "period": 8,
    "category": "unknown, but predicted to be an alkali metal",
    "block": "s"
  }
];